title: Mi Wiki
description: Laboratorio, Wiki y Jardín Digital
theme: just-the-docs

url: https://wiki.bolli.ar

# source: ./docs

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template

# Set a path/url to a favicon that will be displayed by the browser
favicon_ico: "assets/images/favicon.ico"
# Set a path/url to a logo that will be displayed instead of the title
#logo: "./assets/images/favicon.ico"

plugins:
  - jekyll-sitemap
  - github-pages
