title: Mi Wiki
description: Laboratorio, Wiki y Jardín Digital
theme: just-the-docs

url: https://wiki.bolli.ar

aux_links:
  # Template Repository: https://github.com/just-the-docs/just-the-docs-template
